POST http://localhost:3333/videos
Content-Type: application/json
Accept-Language: pt

{
    "title": "Vídeo Java",
    "description": "Esse é o meu primeiro vídeo",
    "duration": 180
}

###

GET http://localhost:3333/videos
Accept-Language: pt

###

GET http://localhost:3333/videos?search=Node
Accept-Language: pt

###

PUT http://localhost:3333/videos/3f4a0dbf-af2a-4836-86bd-015470f57e0a
Content-Type: application/json
Accept-Language: pt

{
    "title": "Vídeo Node.js",
    "description": "Esse é o meu primeiro vídeo",
    "duration": 180
}

###

DELETE http://localhost:3333/videos/3f4a0dbf-af2a-4836-86bd-015470f57e0a
Content-Type: application/json
Accept-Language: pt

{
    "title": "Vídeo 02",
    "description": "Esse é o meu primeiro vídeo",
    "duration": 180
}

###