POST https://node-do-zero-qqcg.onrender.com/videos
Content-Type: application/json
Accept-Language: pt

{
    "title": "Vídeo Java",
    "description": "Esse é o meu primeiro vídeo",
    "duration": 180
}

###

GET https://node-do-zero-qqcg.onrender.com/videos
Accept-Language: pt

###

GET https://node-do-zero-qqcg.onrender.com/videos?search=Node
Accept-Language: pt

###

PUT https://node-do-zero-qqcg.onrender.com/videos/0f5eb823-5e71-4093-bac7-126261e36a01
Content-Type: application/json
Accept-Language: pt

{
    "title": "Vídeo Node.js",
    "description": "Esse é o meu primeiro vídeo",
    "duration": 180
}

###

DELETE https://node-do-zero-qqcg.onrender.com/videos/0f5eb823-5e71-4093-bac7-126261e36a01
Content-Type: application/json
Accept-Language: pt

{
    "title": "Vídeo 02",
    "description": "Esse é o meu primeiro vídeo",
    "duration": 180
}

###